my:
  address: http://localhost  #如果您使用的是本地开发环境，请将此处修改为http://localhost。如果您使用的是服务器，请将此处修改为服务器的域名。
  update-image-url: false  #是否更新表中的图片地址（开启后启动可能会较慢）。
  image:
    #图片保存路径（仅支持相对路径）
    #不填写路径或填写default则保存在当前工作目录下的static/images下
    #填写dev则适合开发环境下不适合打包成jar包
    #填写请填写绝对路径，例如：D:/static/images
    path: D:/static/images
  file:
    path: D:/static/download
server:
  port: 8085
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  mail:
    host: smtp.163.com
    username: xxx@xx.com
    password: 123456
    port: 465
    properties:
      from: username
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      enabled: true
      max-file-size: 10GB
      max-request-size: 10GB
  web:
    resources:
      static-locations: file:D:/static/ #网页存放路径
mybatis-plus:
  mapper-locations: com/smallhowe/mapper/xml/*.xml
